## GamePlay prediction

### Goal: To predict student performance during game-based learning in real-time

- session_id - the ID of the session the event took place in
- index - the index of the event for the session
- elapsed_time - how much time has passed (in milliseconds) between the start of the session and when the event was recorded
- event_name - the name of the event type
- name - the event name (e.g. identifies whether a notebook_click is is opening or closing the notebook)
- level - what level of the game the event occurred in (0 to 22)
- page - the page number of the event (only for notebook-related events)
- room_coor_x - the coordinates of the click in reference to the in-game room (only for click events)
- room_coor_y - the coordinates of the click in reference to the in-game room (only for click events)
- screen_coor_x - the coordinates of the click in reference to the player’s screen (only for click events)
- screen_coor_y - the coordinates of the click in reference to the player’s screen (only for click events)
- hover_duration - how long (in milliseconds) the hover happened for (only for hover events)
- text - the text the player sees during this event
- fqid - the fully qualified ID of the event
- room_fqid - the fully qualified ID of the room the event took place in
- text_fqid - the fully qualified ID of the
- fullscreen - whether the player is in fullscreen mode
- hq - whether the game is in high-quality
- music - whether the game music is on or off
- level_group - which group of levels - and group of questions - this row belongs to (0-4, 5-12, 13-22)

In [7]:
#reading the libraries
import pandas as pd
import numpy as np

In [68]:
#reading the datasets
train_data=pd.read_csv('data/train.csv')

#data_frame.head()
train_data_y

                   session_id  correct
0        20090312431273200_q1        1
1        20090312433251036_q1        0
2        20090312455206810_q1        1
3        20090313091715820_q1        0
4        20090313571836404_q1        1
...                       ...      ...
424111  22100215342220508_q18        1
424112  22100215460321130_q18        1
424113  22100217104993650_q18        1
424114  22100219442786200_q18        1
424115  22100221145014656_q18        1

[424116 rows x 2 columns]

In [80]:
train_data_y=pd.read_csv('data/train_labels.csv')

In [81]:
train_data_y['question_number']=train_data_y['session_id'].str.split('_').str[1].copy()
train_data_y['session_id']=train_data_y['session_id'].str.split('_').str[0].copy()

In [84]:
train_data_y['question_number'].unique()

array(['q1', 'q2', 'q3', 'q4', 'q5', 'q6', 'q7', 'q8', 'q9', 'q10', 'q11',
       'q12', 'q13', 'q14', 'q15', 'q16', 'q17', 'q18'], dtype=object)

In [91]:
train_data['name'].unique()

array(['basic', 'undefined', 'close', 'open', 'prev', 'next'],
      dtype=object)

In [97]:
train_data[train_data['event_name']=='map_hover']

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
127,20090312431273200,127,135124,map_hover,basic,3,NaN,NaN,NaN,NaN,NaN,234.0,NaN,tunic.historicalsociety,tunic.historicalsociety.entry,NaN,0,0,1,0-4
128,20090312431273200,128,135256,map_hover,basic,3,NaN,NaN,NaN,NaN,NaN,17.0,NaN,tunic.kohlcenter,tunic.historicalsociety.entry,NaN,0,0,1,0-4
160,20090312431273200,160,161405,map_hover,basic,4,NaN,NaN,NaN,NaN,NaN,250.0,NaN,toentry,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
161,20090312431273200,161,161822,map_hover,basic,4,NaN,NaN,NaN,NaN,NaN,17.0,NaN,tunic.kohlcenter,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
172,20090312431273200,182,226643,map_hover,basic,5,NaN,NaN,NaN,NaN,NaN,750.0,NaN,toentry,tunic.capitol_0.hall,NaN,0,0,1,5-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296860,22100221145014656,1519,5341715,map_hover,basic,21,NaN,NaN,NaN,NaN,NaN,418.0,NaN,tunic.capitol_2,tunic.wildlife.center,NaN,0,0,1,13-22
26296888,22100221145014656,1547,5375509,map_hover,basic,21,NaN,NaN,NaN,NaN,NaN,568.0,NaN,tobasement,tunic.historicalsociety.entry,NaN,0,0,1,13-22
26296889,22100221145014656,1548,5375959,map_hover,basic,21,NaN,NaN,NaN,NaN,NaN,317.0,NaN,tunic.capitol_2,tunic.historicalsociety.entry,NaN,0,0,1,13-22
26296938,22100221145014656,1597,5482022,map_hover,basic,22,NaN,NaN,NaN,NaN,NaN,1200.0,NaN,tomap,tunic.historicalsociety.entry,NaN,0,0,1,13-22
26296939,22100221145014656,1598,5481765,map_hover,basic,22,NaN,NaN,NaN,NaN,NaN,51.0,NaN,tunic.drycleaner,tunic.historicalsociety.entry,NaN,0,0,1,13-22

In [98]:
train_data[train_data['event_name']=='map_hover'].isnull().sum()

session_id             0
index                  0
elapsed_time           0
event_name             0
name                   0
level                  0
page              945159
room_coor_x       945159
room_coor_y       945159
screen_coor_x     945159
screen_coor_y     945159
hover_duration         0
text              945159
fqid                   0
room_fqid              0
text_fqid         945159
fullscreen             0
hq                     0
music                  0
level_group            0
dtype: int64

In [95]:
train_data[(train_data['session_id']==20090312431273200)&(train_data['level']==1)]

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
28,20090312431273200,28,28113,navigate_click,undefined,1,NaN,-587.657879,-27.916913,441.0,303.0,NaN,NaN,retirement_letter,tunic.historicalsociety.closet,NaN,0,0,1,0-4
29,20090312431273200,29,32229,notification_click,basic,1,NaN,-182.558163,-1.906501,767.0,305.0,NaN,Gramps is in trouble for losing papers?,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.retirement_lett...,0,0,1,0-4
30,20090312431273200,30,33063,notification_click,basic,1,NaN,-182.500704,-55.888296,767.0,359.0,NaN,This can't be right!,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.retirement_lett...,0,0,1,0-4
31,20090312431273200,31,34245,notification_click,basic,1,NaN,-182.486523,-55.883804,767.0,359.0,NaN,Gramps is a great historian!,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.retirement_lett...,0,0,1,0-4
32,20090312431273200,32,36433,object_click,close,1,NaN,-113.484832,241.116732,836.0,62.0,NaN,NaN,retirement_letter,tunic.historicalsociety.closet,NaN,0,0,1,0-4
33,20090312431273200,33,36346,navigate_click,undefined,1,NaN,-453.484720,-193.883232,496.0,497.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
34,20090312431273200,34,36896,navigate_click,undefined,1,NaN,-381.244988,-22.454632,525.0,316.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
35,20090312431273200,35,37445,navigate_click,undefined,1,NaN,-358.832033,54.847822,462.0,249.0,NaN,NaN,tobasement,tunic.historicalsociety.closet,NaN,0,0,1,0-4
36,20090312431273200,36,39845,navigate_click,undefined,1,NaN,-234.247817,-77.052212,245.0,376.0,NaN,NaN,janitor,tunic.historicalsociety.basement,NaN,0,0,1,0-4
37,20090312431273200,37,41297,observation_click,basic,1,NaN,-400.311667,-117.476454,179.0,405.0,NaN,Hmm. Button's still not working.,janitor,tunic.historicalsociety.basement,tunic.historicalsociety.basement.janitor,0,0,1,0-4
38,20090312431273200,38,41898,navigate_click,undefined,1,NaN,-418.370598,-120.264333,172.0,407.0,NaN,NaN,NaN,tunic.historicalsociety.basement,NaN,0,0,1,0-4
39,20090312431273200,39,43413,navigate_click,undefined,1,NaN,-486.265977,-109.112818,151.0,399.0,NaN,NaN,toentry,tunic.historicalsociety.basement,NaN,0,0,1,0-4
40,20090312431273200,40,44196,navigate_click,undefined,1,NaN,385.587985,-135.776680,461.0,413.0,NaN,NaN,groupconvo,tunic.historicalsociety.entry,NaN,0,0,1,0-4
41,20090312431273200,41,45062,cutscene_click,basic,1,NaN,93.811703,-60.345450,338.0,368.0,NaN,Let's get started. The Wisconsin Wonders exhib...,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
42,20090312431273200,42,46046,cutscene_click,basic,1,NaN,133.978871,-85.715094,390.0,386.0,NaN,Who wants to investigate the shirt artifact?,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
43,20090312431273200,43,47362,cutscene_click,basic,1,NaN,125.931445,-83.374177,390.0,385.0,NaN,Not Leopold here. He's been losing papers lately.,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
44,20090312431273200,44,48112,cutscene_click,basic,1,NaN,123.708202,-80.064777,389.0,383.0,NaN,Hey!,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
45,20090312431273200,45,49514,cutscene_click,basic,1,NaN,117.007942,-76.791509,385.0,381.0,NaN,"It's true, they do keep going missing lately.",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
46,20090312431273200,46,50144,cutscene_click,basic,1,NaN,116.997193,-76.790557,385.0,381.0,NaN,See?,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
47,20090312431273200,47,50794,cutscene_click,basic,1,NaN,115.365405,-81.675345,384.0,384.0,NaN,"Besides, I already figured out the shirt.",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
48,20090312431273200,48,52413,cutscene_click,basic,1,NaN,113.735877,-84.931969,383.0,386.0,NaN,It's a women's basketball jersey!,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
49,20090312431273200,49,52328,object_hover,basic,1,NaN,NaN,NaN,NaN,NaN,7899.0,NaN,groupconvo,tunic.historicalsociety.entry,NaN,0,0,1,0-4
50,20090312431273200,50,57277,object_click,basic,1,NaN,856.269358,69.762606,839.0,291.0,NaN,NaN,report,tunic.historicalsociety.entry,NaN,0,0,1,0-4
51,20090312431273200,51,58244,object_click,close,1,NaN,848.127540,401.948788,834.0,87.0,NaN,NaN,report,tunic.historicalsociety.entry,NaN,0,0,1,0-4
52,20090312431273200,52,58845,cutscene_click,basic,1,NaN,296.112267,-106.100667,495.0,399.0,NaN,That settles it.,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
53,20090312431273200,53,59913,cutscene_click,basic,1,NaN,294.483903,-106.100667,494.0,399.0,NaN,"Wells, finish up your report.",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
54,20090312431273200,54,60161,cutscene_click,basic,1,NaN,292.855540,-107.729030,493.0,400.0,NaN,"Leopold, why don't you help me set up in the C...",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
55,20090312431273200,55,60762,cutscene_click,basic,1,NaN,286.342085,-106.100667,489.0,399.0,NaN,We need to talk about that missing paperwork.,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
56,20090312431273200,56,61410,cutscene_click,basic,1,NaN,284.713721,-106.100667,488.0,399.0,NaN,"Will do, Boss.",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
57,20090312431273200,57,61960,cutscene_click,basic,1,NaN,284.713721,-106.100667,488.0,399.0,NaN,"Hey Jo, let's take a look at the shirt!",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
58,20090312431273200,58,62879,cutscene_click,basic,1,NaN,201.667176,-185.890485,437.0,448.0,NaN,undefined,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
59,20090312431273200,59,65459,cutscene_click,basic,1,NaN,279.828631,6.256424,485.0,330.0,NaN,undefined,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4

In [88]:
train_data['session_id'].dtype

dtype('int64')

In [86]:
train_data_y[train_data_y['session_id']=='20090312431273200']

               session_id  correct question_number
0       20090312431273200        1              q1
23562   20090312431273200        1              q2
47124   20090312431273200        1              q3
70686   20090312431273200        1              q4
94248   20090312431273200        1              q5
117810  20090312431273200        1              q6
141372  20090312431273200        1              q7
164934  20090312431273200        1              q8
188496  20090312431273200        1              q9
212058  20090312431273200        1             q10
235620  20090312431273200        1             q11
259182  20090312431273200        1             q12
282744  20090312431273200        0             q13
306306  20090312431273200        1             q14
329868  20090312431273200        1             q15
353430  20090312431273200        0             q16
376992  20090312431273200        1             q17
400554  20090312431273200        1             q18

In [78]:
len(train_data_y.unique())

23562

In [79]:
len(train_data['session_id'].unique())

23562

In [69]:
print(train_data.shape)
print(train_data_y.shape)

(26296946, 20)
(424116, 2)

In [71]:
train_data.head(50)

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
5,20090312431273200,5,3423,person_click,basic,0,NaN,-412.991405,-157.314686,381.0,492.0,NaN,"Sure thing, Jo. Grab your notebook and come up...",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
6,20090312431273200,6,5197,person_click,basic,0,NaN,478.485079,-199.971679,593.0,485.0,NaN,"See you later, Teddy.",teddy,tunic.historicalsociety.closet,tunic.historicalsociety.closet.teddy.intro_0_cs_0,0,0,1,0-4
7,20090312431273200,7,6180,person_click,basic,0,NaN,503.355128,-168.619913,609.0,453.0,NaN,I get to go to Gramps's meeting!,teddy,tunic.historicalsociety.closet,tunic.historicalsociety.closet.teddy.intro_0_cs_0,0,0,1,0-4
8,20090312431273200,8,7014,person_click,basic,0,NaN,510.733442,-157.720642,615.0,442.0,NaN,Now where did I put my notebook?,teddy,tunic.historicalsociety.closet,tunic.historicalsociety.closet.teddy.intro_0_cs_0,0,0,1,0-4
9,20090312431273200,9,7946,person_click,basic,0,NaN,512.048005,-153.743631,616.0,438.0,NaN,\u00f0\u0178\u02dc\u00b4,teddy,tunic.historicalsociety.closet,tunic.historicalsociety.closet.teddy.intro_0_cs_0,0,0,1,0-4
10,20090312431273200,10,9133,navigate_click,undefined,0,NaN,501.110035,-160.748164,605.0,445.0,NaN,NaN,teddy,tunic.historicalsociety.closet,NaN,0,0,1,0-4
11,20090312431273200,11,10263,person_click,basic,0,NaN,501.084991,-164.762366,605.0,445.0,NaN,\u00f0\u0178\u02dc\u00b4,teddy,tunic.historicalsociety.closet,tunic.historicalsociety.closet.teddy.intro_0_cs_5,0,0,1,0-4
12,20090312431273200,12,12030,navigate_click,undefined,0,NaN,510.081490,-106.352093,614.0,386.0,NaN,NaN,photo,tunic.historicalsociety.closet,NaN,0,0,1,0-4
13,20090312431273200,13,13030,observation_click,basic,0,NaN,486.877471,-98.538288,614.0,386.0,NaN,I love these photos of me and Teddy!,photo,tunic.historicalsociety.closet,tunic.historicalsociety.closet.photo,0,0,1,0-4
14,20090312431273200,14,14814,navigate_click,undefined,0,NaN,273.991410,-196.802371,406.0,486.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
15,20090312431273200,15,15498,navigate_click,undefined,0,NaN,185.708460,-205.806533,363.0,492.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
16,20090312431273200,16,16046,navigate_click,undefined,0,NaN,0.583565,-225.691296,234.0,510.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
17,20090312431273200,17,17462,navigate_click,undefined,0,NaN,350.344270,-173.948629,766.0,454.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
18,20090312431273200,18,18164,navigate_click,undefined,0,NaN,-37.961716,-255.711127,301.0,542.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
19,20090312431273200,19,18796,navigate_click,undefined,0,NaN,-133.236752,-251.376033,203.0,531.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
20,20090312431273200,20,19380,navigate_click,undefined,0,NaN,-253.401844,-253.023019,201.0,530.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
21,20090312431273200,21,20014,navigate_click,undefined,0,NaN,-385.096230,-253.134658,197.0,529.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
22,20090312431273200,22,20681,navigate_click,undefined,0,NaN,-564.055739,-216.507416,133.0,492.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
23,20090312431273200,23,21413,navigate_click,undefined,0,NaN,-720.325333,-207.429918,99.0,487.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
24,20090312431273200,24,22013,navigate_click,undefined,0,NaN,-818.128894,-194.244643,92.0,476.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
25,20090312431273200,25,22996,navigate_click,undefined,0,NaN,-924.692590,-254.280542,75.0,539.0,NaN,NaN,notebook,tunic.historicalsociety.closet,NaN,0,0,1,0-4
26,20090312431273200,26,24348,notification_click,basic,0,NaN,-472.142708,-117.942846,554.0,394.0,NaN,Found it!,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.notebook,0,0,1,0-4
27,20090312431273200,27,25766,object_click,close,0,NaN,-206.471467,199.155280,822.0,76.0,NaN,NaN,notebook,tunic.historicalsociety.closet,NaN,0,0,1,0-4
28,20090312431273200,28,28113,navigate_click,undefined,1,NaN,-587.657879,-27.916913,441.0,303.0,NaN,NaN,retirement_letter,tunic.historicalsociety.closet,NaN,0,0,1,0-4
29,20090312431273200,29,32229,notification_click,basic,1,NaN,-182.558163,-1.906501,767.0,305.0,NaN,Gramps is in trouble for losing papers?,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.retirement_lett...,0,0,1,0-4
30,20090312431273200,30,33063,notification_click,basic,1,NaN,-182.500704,-55.888296,767.0,359.0,NaN,This can't be right!,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.retirement_lett...,0,0,1,0-4
31,20090312431273200,31,34245,notification_click,basic,1,NaN,-182.486523,-55.883804,767.0,359.0,NaN,Gramps is a great historian!,NaN,tunic.historicalsociety.closet,tunic.historicalsociety.closet.retirement_lett...,0,0,1,0-4
32,20090312431273200,32,36433,object_click,close,1,NaN,-113.484832,241.116732,836.0,62.0,NaN,NaN,retirement_letter,tunic.historicalsociety.closet,NaN,0,0,1,0-4
33,20090312431273200,33,36346,navigate_click,undefined,1,NaN,-453.484720,-193.883232,496.0,497.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
34,20090312431273200,34,36896,navigate_click,undefined,1,NaN,-381.244988,-22.454632,525.0,316.0,NaN,NaN,NaN,tunic.historicalsociety.closet,NaN,0,0,1,0-4
35,20090312431273200,35,37445,navigate_click,undefined,1,NaN,-358.832033,54.847822,462.0,249.0,NaN,NaN,tobasement,tunic.historicalsociety.closet,NaN,0,0,1,0-4
36,20090312431273200,36,39845,navigate_click,undefined,1,NaN,-234.247817,-77.052212,245.0,376.0,NaN,NaN,janitor,tunic.historicalsociety.basement,NaN,0,0,1,0-4
37,20090312431273200,37,41297,observation_click,basic,1,NaN,-400.311667,-117.476454,179.0,405.0,NaN,Hmm. Button's still not working.,janitor,tunic.historicalsociety.basement,tunic.historicalsociety.basement.janitor,0,0,1,0-4
38,20090312431273200,38,41898,navigate_click,undefined,1,NaN,-418.370598,-120.264333,172.0,407.0,NaN,NaN,NaN,tunic.historicalsociety.basement,NaN,0,0,1,0-4
39,20090312431273200,39,43413,navigate_click,undefined,1,NaN,-486.265977,-109.112818,151.0,399.0,NaN,NaN,toentry,tunic.historicalsociety.basement,NaN,0,0,1,0-4
40,20090312431273200,40,44196,navigate_click,undefined,1,NaN,385.587985,-135.776680,461.0,413.0,NaN,NaN,groupconvo,tunic.historicalsociety.entry,NaN,0,0,1,0-4
41,20090312431273200,41,45062,cutscene_click,basic,1,NaN,93.811703,-60.345450,338.0,368.0,NaN,Let's get started. The Wisconsin Wonders exhib...,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
42,20090312431273200,42,46046,cutscene_click,basic,1,NaN,133.978871,-85.715094,390.0,386.0,NaN,Who wants to investigate the shirt artifact?,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
43,20090312431273200,43,47362,cutscene_click,basic,1,NaN,125.931445,-83.374177,390.0,385.0,NaN,Not Leopold here. He's been losing papers lately.,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
44,20090312431273200,44,48112,cutscene_click,basic,1,NaN,123.708202,-80.064777,389.0,383.0,NaN,Hey!,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
45,20090312431273200,45,49514,cutscene_click,basic,1,NaN,117.007942,-76.791509,385.0,381.0,NaN,"It's true, they do keep going missing lately.",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
46,20090312431273200,46,50144,cutscene_click,basic,1,NaN,116.997193,-76.790557,385.0,381.0,NaN,See?,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
47,20090312431273200,47,50794,cutscene_click,basic,1,NaN,115.365405,-81.675345,384.0,384.0,NaN,"Besides, I already figured out the shirt.",groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
48,20090312431273200,48,52413,cutscene_click,basic,1,NaN,113.735877,-84.931969,383.0,386.0,NaN,It's a women's basketball jersey!,groupconvo,tunic.historicalsociety.entry,tunic.historicalsociety.entry.groupconvo,0,0,1,0-4
49,20090312431273200,49,52328,object_hover,basic,1,NaN,NaN,NaN,NaN,NaN,7899.0,NaN,groupconvo,tunic.historicalsociety.entry,NaN,0,0,1,0-4

In [57]:
#checking the value counts for event_name
data_frame['event_name'].value_counts()

navigate_click        11326433
person_click           6052853
cutscene_click         2703035
object_click           2198211
object_hover           1057085
map_hover               945159
notification_click      649001
notebook_click          564544
map_click               517242
observation_click       212355
checkpoint               71028
Name: event_name, dtype: int64

In [60]:
data_frame.isnull().sum()

session_id               0
index                    0
elapsed_time             0
event_name               0
name                     0
level                    0
page              25732402
room_coor_x        2073272
room_coor_y        2073272
screen_coor_x      2073272
screen_coor_y      2073272
hover_duration    24294702
text              16679807
fqid               8274415
room_fqid                0
text_fqid         16679702
fullscreen               0
hq                       0
music                    0
level_group              0
dtype: int64

In [62]:
data_frame[(data_frame['event_name']!='map_hover')&(data_frame['event_name']!='checkpoint')].isnull().sum()

session_id               0
index                    0
elapsed_time             0
event_name               0
name                     0
level                    0
page              24716215
room_coor_x        1057085
room_coor_y        1057085
screen_coor_x      1057085
screen_coor_y      1057085
hover_duration    24223674
text              15663620
fqid               8274415
room_fqid                0
text_fqid         15663515
fullscreen               0
hq                       0
music                    0
level_group              0
dtype: int64

In [65]:
len(data_frame[data_frame['event_name']=='map_hover'])

945159

In [64]:
data_frame[data_frame['event_name']=='map_hover'].isnull().sum()

session_id             0
index                  0
elapsed_time           0
event_name             0
name                   0
level                  0
page              945159
room_coor_x       945159
room_coor_y       945159
screen_coor_x     945159
screen_coor_y     945159
hover_duration         0
text              945159
fqid                   0
room_fqid              0
text_fqid         945159
fullscreen             0
hq                     0
music                  0
level_group            0
dtype: int64

In [58]:
data_frame[data_frame['event_name']=='notebook_click'].isnull().sum()

session_id             0
index                  0
elapsed_time           0
event_name             0
name                   0
level                  0
page                   0
room_coor_x            0
room_coor_y            0
screen_coor_x          0
screen_coor_y          0
hover_duration    564544
text              564544
fqid              564544
room_fqid              0
text_fqid         564544
fullscreen             0
hq                     0
music                  0
level_group            0
dtype: int64

In [19]:
def null_percentages(data_frame):
    for cols in data_frame.columns:
        null_value_count=data_frame[cols].isnull().sum()
        dataset_len=len(data_frame)
        print('Column Name: ',cols,' Null value percentage: ',(null_value_count/dataset_len)*100)

In [20]:
null_percentages(data_frame)

Column Name:  session_id  Null value percentage:  0.0
Column Name:  index  Null value percentage:  0.0
Column Name:  elapsed_time  Null value percentage:  0.0
Column Name:  event_name  Null value percentage:  0.0
Column Name:  name  Null value percentage:  0.0
Column Name:  level  Null value percentage:  0.0
Column Name:  page  Null value percentage:  97.85319557639887
Column Name:  room_coor_x  Null value percentage:  7.884079010543658
Column Name:  room_coor_y  Null value percentage:  7.884079010543658
Column Name:  screen_coor_x  Null value percentage:  7.884079010543658
Column Name:  screen_coor_y  Null value percentage:  7.884079010543658
Column Name:  hover_duration  Null value percentage:  92.38602079496228
Column Name:  text  Null value percentage:  63.428684836634645
Column Name:  fqid  Null value percentage:  31.465307796578358
Column Name:  room_fqid  Null value percentage:  0.0
Column Name:  text_fqid  Null value percentage:  63.42828555072517
Column Name:  fullscreen  Null value percentage:  0.0
Column Name:  hq  Null value percentage:  0.0
Column Name:  music  Null value percentage:  0.0
Column Name:  level_group  Null value percentage:  0.0

In [21]:
#Remove page column

## Cleaning the data

In [27]:
data_frame[data_frame['level'].isnull()==False]

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0,0,1,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0,0,1,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,22100221145014656,1600,5483231,navigate_click,undefined,22,NaN,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296942,22100221145014656,1601,5485166,navigate_click,undefined,22,NaN,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296943,22100221145014656,1602,5485917,navigate_click,undefined,22,NaN,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296944,22100221145014656,1603,5486753,navigate_click,undefined,22,NaN,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296945,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22

In [33]:
data_frame[['page','level']].groupby('level')['page'].value_counts()

level  page
1      0.0     20199
2      0.0     19766
3      0.0     24244
4      1.0     16287
       0.0      1237
               ...
22     4.0       175
       0.0       122
       3.0       122
       2.0       107
       1.0        96
Name: page, Length: 86, dtype: int64

0.0    19766
Name: page, dtype: int64

In [47]:
for level_val in data_frame['level'].value_counts().index.sort_values():
    print('"Level value": ',level_val)
    for page_val in data_frame[data_frame['level']==level_val]['page'].value_counts().index:
        print('Page value: ',page_val)
    print('----------------------------------------------------------')

"Level value":  0
----------------------------------------------------------
"Level value":  1
Page value:  0.0
----------------------------------------------------------
"Level value":  2
Page value:  0.0
----------------------------------------------------------
"Level value":  3
Page value:  0.0
----------------------------------------------------------
"Level value":  4
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  5
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  6
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  7
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  8
Page value:  2.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  9
Page value:  2.0
Page value:  0.0
Page value:  1.0
----------------------------------------------------------
"Level value":  10
Page value:  2.0
Page value:  3.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  11
Page value:  3.0
Page value:  2.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  12
Page value:  3.0
Page value:  2.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  13
Page value:  3.0
Page value:  2.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  14
Page value:  4.0
Page value:  3.0
Page value:  2.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  15
Page value:  4.0
Page value:  3.0
Page value:  2.0
Page value:  1.0
Page value:  0.0
----------------------------------------------------------
"Level value":  16
Page value:  4.0
Page value:  3.0
Page value:  2.0
Page value:  0.0
Page value:  1.0
----------------------------------------------------------
"Level value":  17
Page value:  4.0
Page value:  3.0
Page value:  2.0
Page value:  0.0
Page value:  1.0
----------------------------------------------------------
"Level value":  18
Page value:  5.0
Page value:  4.0
Page value:  3.0
Page value:  0.0
Page value:  2.0
Page value:  1.0
----------------------------------------------------------
"Level value":  19
Page value:  5.0
Page value:  4.0
Page value:  0.0
Page value:  3.0
Page value:  2.0
Page value:  1.0
----------------------------------------------------------
"Level value":  20
Page value:  6.0
Page value:  5.0
Page value:  4.0
Page value:  0.0
Page value:  3.0
Page value:  2.0
Page value:  1.0
----------------------------------------------------------
"Level value":  21
Page value:  6.0
Page value:  5.0
Page value:  4.0
Page value:  0.0
Page value:  3.0
Page value:  2.0
Page value:  1.0
----------------------------------------------------------
"Level value":  22
Page value:  6.0
Page value:  5.0
Page value:  4.0
Page value:  3.0
Page value:  0.0
Page value:  2.0
Page value:  1.0
----------------------------------------------------------

In [56]:
l4_pg1=data_frame[(data_frame['level']==4)|(data_frame['level']==5)]
#null_percentages(l4_pg1)
l4_pg1.corr()

,session_id,index,elapsed_time,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,fullscreen,hq,music
session_id,1.000000,-0.092591,0.009057,-0.010228,0.002885,-0.003551,0.000856,-0.000670,0.011220,0.000538,0.035793,-0.010257,0.052114
index,-0.092591,1.000000,0.084771,0.109475,0.012515,0.036802,-0.012596,0.065406,-0.000679,-0.000416,-0.018108,0.000596,0.024968
elapsed_time,0.009057,0.084771,1.000000,0.007058,0.006565,0.001515,0.000783,0.002875,-0.002526,-0.000150,0.005103,0.003965,-0.002224
level,-0.010228,0.109475,0.007058,1.000000,0.049085,0.384088,-0.205211,0.599138,0.077866,0.015010,-0.005515,-0.004216,0.002306
page,0.002885,0.012515,0.006565,0.049085,1.000000,-0.187096,0.015680,-0.247870,-0.017946,NaN,-0.027465,-0.011217,-0.015252
room_coor_x,-0.003551,0.036802,0.001515,0.384088,-0.187096,1.000000,-0.074147,0.796879,-0.055438,NaN,-0.005931,-0.005620,0.004601
room_coor_y,0.000856,-0.012596,0.000783,-0.205211,0.015680,-0.074147,1.000000,-0.105214,-0.929363,NaN,0.000623,-0.001241,-0.002773
screen_coor_x,-0.000670,0.065406,0.002875,0.599138,-0.247870,0.796879,-0.105214,1.000000,-0.029710,NaN,0.011804,-0.000029,0.005931
screen_coor_y,0.011220,-0.000679,-0.002526,0.077866,-0.017946,-0.055438,-0.929363,-0.029710,1.000000,NaN,0.047298,0.016107,0.005429
hover_duration,0.000538,-0.000416,-0.000150,0.015010,NaN,NaN,NaN,NaN,NaN,1.000000,-0.002823,-0.001513,0.000166
fullscreen,0.035793,-0.018108,0.005103,-0.005515,-0.027465,-0.005931,0.000623,0.011804,0.047298,-0.002823,1.000000,0.352914,0.003689
hq,-0.010257,0.000596,0.003965,-0.004216,-0.011217,-0.005620,-0.001241,-0.000029,0.016107,-0.001513,0.352914,1.000000,-0.095558
music,0.052114,0.024968,-0.002224,0.002306,-0.015252,0.004601,-0.002773,0.005931,0.005429,0.000166,0.003689,-0.095558,1.000000

In [48]:
data_frame[(data_frame['level']==4)&(data_frame['page']==1.0)].corr()

,session_id,index,elapsed_time,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,fullscreen,hq,music
session_id,1.000000,-0.075517,0.024882,NaN,NaN,-0.009144,0.004980,-0.003489,0.000217,NaN,0.053487,-0.020887,0.073594
index,-0.075517,1.000000,0.203654,NaN,NaN,-0.038839,0.010181,-0.000691,-0.009056,NaN,-0.015682,0.005638,0.006728
elapsed_time,0.024882,0.203654,1.000000,NaN,NaN,-0.007074,-0.000395,0.001696,-0.000582,NaN,-0.009330,-0.011447,-0.003272
level,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
page,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
room_coor_x,-0.009144,-0.038839,-0.007074,NaN,NaN,1.000000,0.719845,0.829605,-0.715754,NaN,-0.011240,-0.010126,-0.013320
room_coor_y,0.004980,0.010181,-0.000395,NaN,NaN,0.719845,1.000000,0.869718,-0.993665,NaN,-0.011423,0.004385,-0.006653
screen_coor_x,-0.003489,-0.000691,0.001696,NaN,NaN,0.829605,0.869718,1.000000,-0.863301,NaN,-0.002718,-0.005030,-0.004156
screen_coor_y,0.000217,-0.009056,-0.000582,NaN,NaN,-0.715754,-0.993665,-0.863301,1.000000,NaN,0.027223,-0.002229,0.007770
hover_duration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
fullscreen,0.053487,-0.015682,-0.009330,NaN,NaN,-0.011240,-0.011423,-0.002718,0.027223,NaN,1.000000,0.336918,0.006072
hq,-0.020887,0.005638,-0.011447,NaN,NaN,-0.010126,0.004385,-0.005030,-0.002229,NaN,0.336918,1.000000,-0.099491
music,0.073594,0.006728,-0.003272,NaN,NaN,-0.013320,-0.006653,-0.004156,0.007770,NaN,0.006072,-0.099491,1.000000

In [25]:
#page and level has high correlation

In [67]:
#getting the data with the levels 4,12 and 22.
data_frame[(data_frame['level']==4)|(data_frame['level']==12)|(data_frame['level']==22)]

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,fullscreen,hq,music,level_group
152,20090312431273200,152,156239,navigate_click,undefined,4,NaN,337.732330,-51.000000,348.0,381.0,NaN,NaN,NaN,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
153,20090312431273200,153,156838,navigate_click,undefined,4,NaN,30.196745,-51.000000,95.0,381.0,NaN,NaN,NaN,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
154,20090312431273200,154,157439,navigate_click,undefined,4,NaN,-157.073154,-65.000000,35.0,395.0,NaN,NaN,NaN,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
155,20090312431273200,155,157972,navigate_click,undefined,4,NaN,-301.805255,-72.000000,34.0,402.0,NaN,NaN,NaN,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
156,20090312431273200,156,158683,navigate_click,undefined,4,NaN,-467.567269,-51.000000,33.0,381.0,NaN,NaN,NaN,tunic.kohlcenter.halloffame,NaN,0,0,1,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,22100221145014656,1600,5483231,navigate_click,undefined,22,NaN,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296942,22100221145014656,1601,5485166,navigate_click,undefined,22,NaN,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296943,22100221145014656,1602,5485917,navigate_click,undefined,22,NaN,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296944,22100221145014656,1603,5486753,navigate_click,undefined,22,NaN,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22
26296945,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,0,0,1,13-22